### ISSUE TITLE
katago 20b and new optimized 40b running abnormally slow

### ISSUE THREAD

**Issue by humble-stu** [aki65/aki65.github.io#61] opened 2022-03-27 11:20 UTC
katago 10b and leela zero work normally on mi 11，snapdragon888，above 100 visits per sec，but katago 20b and 40b only have 10 visits per sec speed，bug or feature？

**Comment by aki65** [comment] 2022-03-27 14:28
I have a mi 11 myself, and I had the same issue after updating to MIUI 13. But this problem should be solved (at least it was on my phone) if you
- use the latest release of BadukAI from https://github.com/aki65/aki65.github.io/releases/tag/v1.15.0
- use the latest 40b network from https://github.com/aki65/aki65.github.io/releases/tag/v1.13.2

**Comment by humble-stu** [comment] 2022-03-28 02:27
Yes I use latest version, but i didn't  update miui 13, still 12.5, do I need to update?

**Comment by aki65** [comment] 2022-03-28 20:02
No, you don't need to update. When I had MIUI 12.5, I was using
- BadukAI 1.13 ( from https://github.com/aki65/aki65.github.io/releases/tag/v1.13.0 )
- 40b network from https://github.com/aki65/aki65.github.io/releases/tag/v1.13.1

and this combination worked well (so should also work for you).

If you don't need the built-in 20b network, BadukAI 1.15 with the 40b network from above should also work.

By the way, I'm sorry, I don't speak chinese. My answer in the other thread (which probably gave that impression) was created by google translate. So we should stick to english ...

**Comment by humble-stu** [comment] 2022-03-29 04:05
LOL，Google translation works good.  By the way, the computation speed on phone really surprises me, I run the same katago 40b on 1060, only about 200 visits/s or less. 
The numofsearchthread, nncachesizePoweroftwo, playingoutdoubleadvantage, just keep it default?

**Comment by aki65** [comment] 2022-03-29 22:08
Changing the cache size is only necessary if your device has not much RAM (which is of course not the case on Mi 11). PlayoutDoublingAdvantage should only be changed for handicap games. 

For best performance, you should tick parallelEvaluation and set numSearchThreads = 2. This should yield around 80 visits/s for 40b. And if you are really keen on performance, you should upgrade to MIUI 13, because it is based on android 12 which brings the latest chipset drivers. Then you will get around 135 visits/s with the latest 40b network.

**Comment by humble-stu** [comment] 2022-03-30 03:22
I upgrade to miui 13, seems it is easier to make mi11 overheat.
I thought numofsearchthread bigger, performance better, at least on PC katago, not 2.

**Comment by aki65** [comment] 2022-03-30 21:49
> I thought numofsearchthread bigger, performance better, at least on PC katago, not 2, curious. 

According to my tests, adding more threads than 2 doesn't increase performance any more. Probably, this is because a smartphone NPU has much fewer cores than a PC graphics card (so that it is already kept busy by much fewer threads).

> By the way, when I use analyze all to play manual, about 100 round plays, the program stuck, is it inevitable？

I never had that problem. Can you share the sgf where it happens ? And tell me what's the exact sequence of steps to reproduce that ?

> Find some problem about AI predicted winrate, sometimes I play one 20% winrate hand on white, which means white's winrate should be 80%, then analyze black winrate suddenly fall to 68%. Continue to compute doesn't help, even up to 30k visit.

One move later KataGo also looks one move further ahead (on average with same number of visits). So it may detect a good move for white which it overlooked in the analysis of the previous position. And this may reduce black's winrate from 80% to 68%.

**Comment by ugvvff** [comment] 2022-04-02 07:48
865处理器手机在更新安卓12也会有运行速度的提升吗？

**Comment by ugvvff** [comment] 2022-04-02 07:48
865处理器手机在更新安卓12也会有运行速度的提升吗？

**Comment by humble-stu** [comment] 2022-04-03 07:25
Not a specific sgf, just any random analysis, seems the APP can't support long analysis, or it will crash. The compute speed for 40b fall to 60 visits/s these days, inexplicable.
I think it is not persuasive to me, it is a loacl live or dead problem

**Comment by aki65** [comment] 2022-04-03 15:49
I analyzed some complete games, but could not reproduce the crash. Perhaps there is a memory problem after long analysis, so you could try reducing the cache size by setting nnCacheSizePowerofTwo = 10.

The compute speed may indeed decrease during a long analysis due to thermal throttling.

**Comment by aki65** [comment] 2022-04-03 18:17
不，我不期望如此。865出现在安卓10中，所以所有的驱动优化和错误修复都将在安卓11中完成，所以在安卓12中没有进一步的改进可言。

**Comment by ivysrono** [comment] 2022-06-03 03:58
@aki65 Redmi Note 11T Pro which with Dimensity8100 and MIUI13 no NPU works by 1.15.0 and 1.15.2, only about 22n/s.

**Comment by aki65** [comment] 2022-06-03 15:45
As NPU acceleration works on Dimensity 1100 and Dimensity 9000, this is clearly a bug in the NPU driver of Dimensity 8100. So we can only hope that this is fixed with an upcoming firmware update. Since the phone is so new, there will surely be some of those in the near future.

**Comment by ivysrono** [comment] 2022-06-10 14:04
> As NPU acceleration works on Dimensity 1100 and Dimensity 9000, this is clearly a bug in the NPU driver of Dimensity 8100. So we can only hope that this is fixed with an upcoming firmware update. Since the phone is so new, there will surely be some of those in the near future.

Need to check 3 or 4 .

**Closed** 2022-09-11 14:42 UTC
